---
# Ensure stack nodes are ready for installation
- hosts: stack_nodes
  tasks:
    - name: Wait for cloud-init to complete
      wait_for: path="/var/lib/cloud/instance/boot-finished" state=present

# Apply common settings to all nodes prior to installation
- hosts: stack_nodes
  roles:
    - system/ubuntu

# Include stack playbooks. Only the configured stack will be installed.
- include: config.devstack.yml
# - include: config.openstack.yml
- include: config.kubernetes.yml

# Install Romana
- hosts: controller
  roles:
    - romana/install-master
    - romana/postinstall

# Install and launch agent
- hosts: stack_nodes
  roles:
    - romana/install-agent

# Include romana+stack playbooks. Only the configured stack will be applied
- include: romana.devstack.yml
# - include: romana.openstack.yml
- include: romana.kubernetes.yml

# Generate a summary
- hosts: localhost
  roles:
    - summary
