---
- name: Install romana-root upstart service
  template: src="romana-root.conf" dest="/etc/init/romana-root.conf" mode=0644

# The "root" service needs to be launched so that the first-run can be performed
- name: Launch romana-root
  service: name="romana-root" state="started"

# The first-run is required for these services to create the database schema.
- name: Execute first-run for other services
  shell: "{{ romana_dir }}/bin/{{ item }} -overwriteSchema -rootURL http://{{ stack_nodes.Controller.mgmt_ip }}:9600"
  with_items:
    - ipam
    - tenant
    - topology

- name: Install other romana upstart services
  template: src="romana-{{ item }}.conf" dest="/etc/init/romana-{{ item }}.conf" mode=0644
  with_items:
    - ipam
    - tenant
    - topology

# All services are installed, and dependent on the "root" service.
# To activate them, a restart of the root service brings them all up.
- name: Restart romana-root
  service: name="romana-root" state="restarted"
