---
- name: Create demo directory
  file: path="/home/{{ ansible_ssh_user }}/demo/" mode=0775 state=directory

- name: Install additional tools (required for demo script)
  include: "{{ item }}"
  with_first_found:
    - files: 
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  become: true
  become_user: root

- name: Copy examples and demo script to demo directory
  copy: src="demo/{{ item }}" dest="/home/{{ ansible_ssh_user }}/demo/{{ item }}"
  with_items:
    - example-controller.yaml
    - namespace-tenant-a.yaml
    - pod-backend.yaml
    - pod-frontend.yaml
    - romana-np-frontend-to-backend.json

- name: Install and make demo script executable
  template: src="demo.sh" dest="/home/{{ ansible_ssh_user }}/demo/demo.sh" mode=0755
